name: Run tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop, 'hotfix/*', 'feature/*' ]

# Cancel job when new commit is pushed for the same build
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
# https://github.com/OSGeo/gdal/pull/5460
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node }}
# We need package-lock.json to use cache this way
#          cache: 'npm'
      - name: Install dependencies
# With package-lock.json we should use "npm ci"
        run: npm install
      - run: npm test
